version: "3.8"
services:
  # POSTGRES************************************
  postgres:
    image: postgres:12.2
    container_name: postgres
    networks:
      - kafka-cluster-network
    volumes:
      - postgres-data:/var/lib/postgresql/storage/data
    expose:
      - 5432
    ports:
      - 5432:5432
    command: -p 5432 -c wal_level=logical
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=debezium_db
    restart: unless-stopped

  # ZOOKEEPER************************************
  zookeeper:
    image: bitnami/zookeeper:3.6.3
    container_name: zookeeper
    networks:
      - kafka-cluster-network
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    expose:
      - 2181
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  # KAFKA************************************
  kafka:
    image: bitnami/kafka:3.2.1
    container_name: kafka
    networks:
      - kafka-cluster-network
    volumes:
      - kafka-data:/bitnami/kafka
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9094,OUTSIDE://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9094,OUTSIDE://127.0.0.1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    depends_on:
      - zookeeper

  # POSTGRES-CONNECTOR************************************
  postgres-connector:
    image: debezium/connect:latest
    container_name: postgres-connector
    networks:
      - kafka-cluster-network
    expose:
      - 8083
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9094
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres

volumes:
  kafka-data:
  zookeeper-data:
  postgres-data:

networks:
  kafka-cluster-network:
    driver: bridge